---
- hosts: mywebservers
  become: yer
  tasks:
  - name: install java on ubantu nodes
    apt:
      name: "{{myjavainstallonubantu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat nodes
    yum:
      name: "{{myjavainstallonredhat}}"
      state: present 
    when: ansible_os_family =="RedHat"   