---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubantu ansible nodes
    apt:
      name: apache2
      state: present

  - name: start webserver on ubantu ansible nodes
    apt:
      name: apache2
      state: started